In [1]:
import querys_feitas as qf
import pandas as pd
from bson.objectid import ObjectId

In [2]:
dict_query = { "$and": [{"id_experimento": ObjectId("5ea1a82993f4d56ba41e567d")}, 
                        {"var_ind.sexo":"macho"},
                        {"var_ind.dosagem": "flx2.5mg"}]}


cs = qf.Get_CSV(dict_query)
li_str_descritores = ["duracao", "frequencia"]
li_str_categora = ["Immobility", "Swimming"]

data = cs.set_descritores_experimentais(li_str_descritores, li_str_categora )
# print(data["5ea1d2d793f4d539f4d5e907"])

In [3]:
def get_keys(array):
    return array[0]

keys =[]
for d in data[0]:
    keys.append(list(d.keys()))

keys = list(map(get_keys,keys))
print(keys)

['d_e_Immobility_s', 'f_e_Immobility_s', 'd_e_Swimming_s', 'f_e_Swimming_s', 'id_eto', 'id_j']

In [4]:
def cons_map_by_key(key):
    def map_va(data):
        return data[key]
    return map_va
    
dic = {}
for i,key in enumerate(keys):
    d= []
    for juncao in data:
        d.append(juncao[i])
        dic[keys[i]]= list(map(cons_map_by_key(keys[i]),d))

# print(list(map(cons_map_by_key(keys[0]),d)))

In [5]:
keys[0]
# d[0]
dic

{'d_e_Immobility_s': [31.466666666666665,
  34.56666666666667,
  47.9,
  33.6,
  47.46666666666667,
  119.9,
  64.63333333333334,
  87.96666666666667,
  79.46666666666667,
  92.46666666666667,
  92.23333333333333,
  92.66666666666667],
 'f_e_Immobility_s': [41, 44, 54, 38, 53, 61, 45, 105, 81, 81, 90, 83],
 'd_e_Swimming_s': [8.633333333333333,
  10.366666666666667,
  6.166666666666667,
  13.8,
  8.5,
  10.4,
  12.966666666666667,
  22.5,
  23.533333333333335,
  16.9,
  25.3,
  25.733333333333334],
 'f_e_Swimming_s': [17, 19, 22, 15, 24, 34, 29, 57, 43, 40, 53, 49],
 'id_eto': ['5ea2305793f4d55ef029829b',
  '5ea2305793f4d55ef02982a4',
  '5ea2305793f4d55ef02982ad',
  '5ea2305893f4d55ef02982b6',
  '5ea2305893f4d55ef02982bf',
  '5ea2305893f4d55ef02982c8',
  '5ea2305993f4d55ef02982d1',
  '5ea2305993f4d55ef02982da',
  '5ea2305993f4d55ef02982e3',
  '5ea2305a93f4d55ef02982ec',
  '5ea2305a93f4d55ef02982f5',
  '5ea2305a93f4d55ef02982fe'],
 'id_j': ['5ea2305793f4d55ef0298297',
  '5ea2305793f4d55ef02982a0',
  '5ea2305793f4d55ef02982a9',
  '5ea2305893f4d55ef02982b2',
  '5ea2305893f4d55ef02982bb',
  '5ea2305893f4d55ef02982c4',
  '5ea2305993f4d55ef02982cd',
  '5ea2305993f4d55ef02982d6',
  '5ea2305993f4d55ef02982df',
  '5ea2305a93f4d55ef02982e8',
  '5ea2305a93f4d55ef02982f1',
  '5ea2305a93f4d55ef02982fa']}

In [6]:
df = pd.DataFrame(dic)
df

,d_e_Immobility_s,f_e_Immobility_s,d_e_Swimming_s,f_e_Swimming_s,id_eto,id_j
0,31.466667,41,8.633333,17,5ea2305793f4d55ef029829b,5ea2305793f4d55ef0298297
1,34.566667,44,10.366667,19,5ea2305793f4d55ef02982a4,5ea2305793f4d55ef02982a0
2,47.900000,54,6.166667,22,5ea2305793f4d55ef02982ad,5ea2305793f4d55ef02982a9
3,33.600000,38,13.800000,15,5ea2305893f4d55ef02982b6,5ea2305893f4d55ef02982b2
4,47.466667,53,8.500000,24,5ea2305893f4d55ef02982bf,5ea2305893f4d55ef02982bb
5,119.900000,61,10.400000,34,5ea2305893f4d55ef02982c8,5ea2305893f4d55ef02982c4
6,64.633333,45,12.966667,29,5ea2305993f4d55ef02982d1,5ea2305993f4d55ef02982cd
7,87.966667,105,22.500000,57,5ea2305993f4d55ef02982da,5ea2305993f4d55ef02982d6
8,79.466667,81,23.533333,43,5ea2305993f4d55ef02982e3,5ea2305993f4d55ef02982df
9,92.466667,81,16.900000,40,5ea2305a93f4d55ef02982ec,5ea2305a93f4d55ef02982e8
10,92.233333,90,25.300000,53,5ea2305a93f4d55ef02982f5,5ea2305a93f4d55ef02982f1
11,92.666667,83,25.733333,49,5ea2305a93f4d55ef02982fe,5ea2305a93f4d55ef02982fa